### PR TITLE
fix bug

### PR DESCRIPTION
**Pull request by bafflingbug**
emmm

### CODE REVIEW

**Comment by lwl12** [comment]
Hummm看起来还是有点问题，我这后台原有的歌展示不了了，也没办法新增歌曲……

感觉还是数据库更新的问题= =

**Comment by bafflingbug** [comment]
<code>

<script>
   var hermit = {
   catList: [{"id":"1","title":"\u672a\u5206\u7c7b","count":2}],
   count: 2,
   prePage: 20,
   maxPage: 1,
   adminUrl: 'https://blog.bafflingbug.cn/wp-admin/admin-ajax.php?action=hermit_source',
   data: [{"id":"2","song_name":"\u7ae5\u8bdd\u9547","song_author":"\u9648\u4e00\u53d1\u513f","song_cat":"1","song_url":"http:\/\/other.web.rp01.sycdn.kuwo.cn\/resource\/n3\/47\/22\/3150923806.mp3","song_cover":"https:\/\/blog.bafflingbug.cn\/wp-content\/uploads\/2018\/08\/\u7ae5\u8bdd\u9547-\u9648\u4e00\u53d1\u513f.jpg","song_lrc":""},{"id":"1","song_name":"\u963f\u5a46\u8bf4","song_author":"\u9648\u4e00\u53d1\u513f","song_cat":"1","song_url":"http:\/\/other.web.ri01.sycdn.kuwo.cn\/resource\/n1\/96\/6\/74950139.mp3","song_cover":"https:\/\/blog.bafflingbug.cn\/wp-content\/uploads\/2018\/08\/\u963f\u5a46\u8bf4-\u9648\u4e00\u53d1\u513f.jpg","song_lrc":""}],
   currentCatId: 0		};
   </script>

</code>

**Comment by lwl12** [comment]
@bafflingbug 这就是了……我这里 data 是空的

**Comment by bafflingbug** [comment]
/wp-admin/admin-ajax.php?action=hermit_source&type=list&paged=1
看下这个地址返回的信息呢？也是看data

**Comment by lwl12** [comment]
@bafflingbug 也是空的（

**Comment by bafflingbug** [comment]
emmm，如果确定数据库不是空的。
大概还是增加数据库字段的代码没被执行。。。
去数据库看下吧

如果是如此，禁用后再启用应该能解决问题

**Comment by lwl12** [comment]
hummm看来还是要改一下更新逻辑 @Bing072

**Comment by lwl12** [comment]
@bafflingbug 看了下禁用再启用确实恢复了

**Comment by bafflingbug** [comment]
3.1 : This hook is now fired only when the user activates the plugin and not when an automatic plugin update occurs (#14915).

From https://codex.wordpress.org/Function_Reference/register_activation_hook
emmm 我好像看的是一个老版本的教程

**Pull request merged**
